#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: 127.0.0.1
    password: 123456
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      web-context-unify: true   #关闭web-context整合
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
    retries: 0
tanhua:
  sms:
    signName: 物流云商
    templateCode: SMS_106590012
    accessKey: LTAI4GKgob9vZ53k2SZdyAC7
    secret: LHLBvXmILRoyw0niRSBuXBZewQ30la
  oss:
    accessKey: LTAI5tGeXtba84DP429gTT4P
    secret: qpjNlMfGiII7iMnjXHUTUtza7PvlYU
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: tanhua-zrm
    url: https://tanhua-zrm.oss-cn-beijing.aliyuncs.com/
  aip:
    appId: 25493537
    apiKey: 1QFR1TeN14FpipU3xzLbRuM9
    secretKey: UZohgtYLHCTENTYrc0nNN2Wm1RgTg91c